### ISSUE TITLE
node:16672) ExperimentalWarning from win exe version

### ISSUE THREAD

**Issue by Spineshark147** [nielsmaerten/ynab-buddy#251]
**Describe the bug**
Hi, I was so excited when I saw this. Thanks for creating. Unfortunatly I get an error when I run the win version https://github.com/nielsmaerten/ynab-buddy/releases/download/v2.0.1/ynab-buddy-win.exe.

I downloaded the win 2.0.1 and added it to a new folder c:\ynabbaddy\ then run the exe and I get this error:

(node:16672) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `ynab-buddy-win (1) --trace-warnings ...` to show where the warning was created)

Im not experienced with code so might just be my machine. 
Do you perhaps have any advice as to the problem?
Thank you

**Screenshots**
![image](https://github.com/nielsmaerten/ynab-buddy/assets/31993765/f94b0dd8-d0bc-477b-97d8-26e73fa19e27)

**Desktop (please complete the following information):**
 - OS: Win 10 
 - Version 22H2
 - Did you install ynab-buddy using NPM? no

**Comment by nielsmaerten** [comment]
Hi @Spineshark147 

Before you can start using ynab-buddy, you'll need to teach it how to read your bank's CSV files.  
Check your user folder (for me, that would be `C:/Users/niels/ynab-buddy`)  

In this folder, you should find a file called `config.yaml` with instructions on how to configure ynab-buddy.  
Once you have filled out your settings in this file, try running `ynab-buddy-win.exe` again.

**Comment by Spineshark147** [comment]
Thank you for the quick reply. Now it all makes sence. I updated your readme to be a bit clearer, hope that is okay. 
The warning still sits there but its not stopping anything.
![image](https://github.com/nielsmaerten/ynab-buddy/assets/31993765/a8c371ac-d89f-4848-8f73-3a08f65154e6)
All working. Thanks.
